sudo: false
language: node_js
node_js:
  - "6"

cache:
  directories:
    - node_modules

install:
  - npm install

script:
  - npm run deploy:prod

after_success:
  - npm run codecov

deploy:
  provider: azure_web_apps
  file:
    - "app.js"
    - "dist/*"
    - "package.json"
  verbose: true
